version: '3.8'

# Development overrides for docker-compose.yml
services:
  backend:
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true