version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: fleetmanager_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-fleetmanager123}
      MONGO_INITDB_DATABASE: fleetmanager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - fleetmanager_network_dev

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleetmanager_backend_dev
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://root:${MONGO_PASSWORD:-fleetmanager123}@mongodb:27017/${DB_NAME:-fleetmanager}?authSource=admin
      - DB_NAME=${DB_NAME:-fleetmanager}
      - JWT_SECRET_KEY=${JWT_SECRET:-your-super-secret-jwt-key-for-development}
      - ENVIRONMENT=development
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - fleetmanager_network_dev

  # Frontend Web App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleetmanager_frontend_dev
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost:8001}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fleetmanager_network_dev
    stdin_open: true
    tty: true

volumes:
  mongodb_data_dev:
    driver: local

networks:
  fleetmanager_network_dev:
    driver: bridge