version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: fleet_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: fleet_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fleet_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleet_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=fleet_db
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - fleet_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleet_frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fleet_network

volumes:
  mongodb_data:

networks:
  fleet_network:
    driver: bridge